require 'rake/extensiontask'


spec = Gem::Specification.new do |s|
  s.name        = 'backproprb'
  s.version     = '0.0.1'
  s.date        = '2013-04-20'
  s.summary     = "Backpropagation Neural Network"
  s.description = "A gem for training and running Backprop Neural Networks"
  s.authors     = ["Joshua Petitt"]
  s.email       = 'joshpetitt@jpmec.com'
  s.homepage    = 'https://github.com/jpmec/ann'
  s.files       = Dir.glob('lib/**/*.rb') +
                  Dir.glob('ext/**/*.{h,c}')
  s.extensions  = ['ext/backproprb/extconf.rb']
  s.test_files  = ['test/test_backproprb.rb']
end


Gem::PackageTask.new(spec) do |pkg|
end


# feed the ExtensionTask with your spec
Rake::ExtensionTask.new('backproprb', spec)


task :test do

  puts `ruby test/test_backproprb.rb`

end


task :default do

  puts `gem uninstall backproprb`

  puts `rake clobber`
  puts /error/.match(`rake compile`)
  puts `rake gem`
  puts `rake package`

  puts `gem install pkg/backproprb`

#  puts `ruby test/test_backproprb.rb`

end
